Add support for attachments api
nylas/nylas-nodejs pull request #505
Opened 2023-11-22 22:17 UTC by yifanplanet

- Add support for attachments api

# License
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-12-01 21:02 UTC, mrashed-dev requested changes
Awesome work @yifanplanet! Left some comments.

2023-12-01 21:02 UTC, mrashed-dev commented on src/models/attachments.ts
> +export type DownloadAttachmentQueryParams = Partial<FindAttachmentQueryParams>;
This shouldn't be a partial, messageId is required in both attachment calls. 

```suggestion
export type DownloadAttachmentQueryParams = FindAttachmentQueryParams;
```

2023-12-01 21:02 UTC, mrashed-dev commented on src/resources/attachments.ts
> + * You can also send attachments inline in an email message, for example for images that should be displayed in the email body content.
nit: I think this is not needed

2023-12-05 18:43 UTC, yifanplanet commented
> Awesome work @yifanplanet! Left some comments.

@mrashed-dev Thanks for the review! Updates were made based on the requests.

2023-12-21 02:17 UTC, merged